### ISSUE TITLE
TypeError: Cannot read property 'then' of undefined

### ISSUE THREAD

**Issue by emufan** [thomasloven/lovelace-card-mod#135]
My Home Assistant version: 2021.7.1

My lovelace configuration method (GUI or yaml): both

**Minimal** steps to reproduce:
Click on any entity to open detail popup. Every click will result in the error message below. The popup is then working, but an error on each click seam to be not the best.

Error messages from the browser console:

```
card-mod.js:5 Uncaught (in promise) TypeError: Cannot read property 'then' of undefined
    at HTMLElement.e.showDialog (card-mod.js:5)
    at o (app.62541dd1.js:34265)
e.showDialog @ card-mod.js:5
o @ app.62541dd1.js:34265
async function (async)
o @ app.62541dd1.js:34265
_handleMoreInfo @ app.62541dd1.js:36082
(anonymous) @ app.62541dd1.js:36082
i @ app.62541dd1.js:13499
u @ chunk.aae0ef6cbcb20bdba24f.js:322
value @ chunk.aae0ef6cbcb20bdba24f.js:1528
handleEvent @ app.62541dd1.js:13499
i @ app.62541dd1.js:13499
e.actionHandler.t.disabled.e.actionHandler.end @ chunk.aae0ef6cbcb20bdba24f.js:322
```
---

**By putting an X in the boxes ([]) below, I indicate that I:**

- [x] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [x] Have made sure I am using the latest version of the plugin.

- [x] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [x] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by JoshuaRedmond** [comment]
I'm also experiencing this. From looking around, I believe this was previously reported in [Issue 128](https://github.com/thomasloven/lovelace-card-mod/issues/128), and fixed in [8e99e21](https://github.com/thomasloven/lovelace-card-mod/commit/8e99e2104c7cd9a3c346d3b021400707b7e57b7c), but there hasn't been a release since then so the issue still persists.

**Comment by Final-Hawk** [comment]
I have the same issue. Looking for a fix. disabling card mod fixes it. Happens when any dialog box is opened in the UI

**Comment by emufan** [comment]
Error still there, even with the newest updates 3.0.12 and 3.0.13. Any chance to have this fixed?

**Comment by emufan** [comment]
Didn't see these errors anymore.
