### ISSUE TITLE
entities cards need extra refesh for theme to load correctly (using card-mod-theming)

### ISSUE THREAD

**Issue by Mariusthvdb** [thomasloven/lovelace-card-mod#183]
My Home Assistant version: 2022.4.0.dev20220226

My lovelace configuration method (GUI or yaml): Yaml
Card-mod 3.2.1 installed via
```
frontend:
  themes: !include_dir_merge_named /config/frontend_themes

  extra_module_url:
    - /local/lovelace/resources/lovelace-card-mod/card-mod.js
```

What I am doing:
related to https://github.com/home-assistant/frontend/issues/10988#issuecomment-1052134096

changing themes in Lovelace, and have card-mod-theme in place

What I expected to happen:

all cards changing theme

What happened instead:

when changing themes, entities cards need an extra refresh to load the new theme. A reload of the page solves this.
**Minimal** steps to reproduce:

```yaml
# The least amount of code possible to reproduce my error, having 

Dark blue:

  <<: &generic
    card-mod-theme: custom-header
# rest of these settings
# End of code
```

Error messages from the browser console:

---

with card-mod-theme line, needs reload for theme change on entities:

![Feb-26-2022 16-51-41](https://user-images.githubusercontent.com/33354141/155849675-af155397-f23b-4bb6-a065-c7db806e25f6.gif)

without, direct theme change on all, including entities:

![Feb-26-2022 16-54-25](https://user-images.githubusercontent.com/33354141/155849754-50485e65-71ab-45cf-8629-23070cdfb7ec.gif)

**By putting an X in the boxes ([]) below, I indicate that I:**

- [X] Understand that this is a channel for reporting bugs, not a support forum (https://community.home-assistant.io/).

- [X] Have made sure I am using the latest version of the plugin.

- [X] Have followed the troubleshooting steps of the "Common Problems" section of https://github.com/thomasloven/hass-config/wiki/Lovelace-Plugins.

- [X] Understand that leaving one or more boxes unticked or failure to follow the template above may increase the time required to handle my bug-report, or cause it to be closed without further action.

**Comment by tomlut** [comment]
Similar issue? https://github.com/thomasloven/lovelace-card-mod/issues/163

**Comment by tomlut** [comment]
Sadly, not for me.

**Comment by Mariusthvdb** [comment]
aw thats too bad, just checked it again and can only say in any browser, including Safari (!) the themes change correctly.

I do notice this small theme-mod no longer being functional
```
christmas-theme:
  card-mod-theme: christmas-theme
  <<: *main
  card-mod-card: |
    ha-card {
      overflow: hidden;
    }
```

and all of my cards in that theme now show:
<img width="402" alt="Schermafbeelding 2022-03-16 om 11 56 41" src="https://user-images.githubusercontent.com/33354141/158574798-83d03336-ee6d-4e97-ba03-3c29c106785c.png">

the overflow at the top corners

**Comment by Mariusthvdb** [comment]
not sure if we still need this? I can no duplicate any longer. 2024.3 (beta) and all is ok.
Tom could you please check, Id rather close if it were for me

**Comment by tomlut** [comment]
Yeah it's still broken for me. If I have a view open when my theme changes from day to night or vice versa I get a weird combination of both that needs a page refresh to fix.

**Comment by Mariusthvdb** [comment]
@tomlut Tom, any progress on the matter?

personally id like to close as not experiencing any more since posted above. now on 2024.8, I hope this is fixed for you too?

**Comment by tomlut** [comment]
I won't have time to update until the weekend. However at the moment it is very much still broken (2022.7).

**Comment by tomlut** [comment]
Just updated. It is still an issue on 2024.8 but honestly I don;t care. Close it if you want Marius. I'm going to be stripping out all my card-mod theming and just go with the plain core theme. Far too much hassle to keep it all working.

**Comment by Mariusthvdb** [comment]
ok, let me do that then, I really can't break it anymore, maybe there indeed is something in your specific theme-mods that is no longer functional.

Let me close, and if you find yourself wanting again, I can re-open.

cleaning up my own issues....
